#ifndef FSM_H
#define FSM_H

#include "buttons.h"
#include "bluetooth.h"
#include "motors.h"
#include "rfid.h"

/* Defines for states of FSM */

#define LEFT_CRATE_STATE 0
#define RIGHT_CRATE_STATE 1
#define TOP_CRATE_STATE 2
#define BOTTOM_CRATE_STATE 3
#define IDLE_STATE 4
#define OPEN_STATE 5
#define CLOSE_STATE 6
#define EMPTY_CENTER_STATE 7
#define ERROR_STATE 8

/* Defines for signals of FSM */

#define LEFT_CRATE_SIGNAL 0
#define RIGHT_CRATE_SIGNAL 1
#define TOP_CRATE_SIGNAL 2
#define BOTTOM_CRATE_SIGNAL 3
#define IDLE_SIGNAL 4
#define OPEN_SIGNAL 5
#define CLOSE_SIGNAL 6
#define EMPTY_CENTER_SIGNAL 7

/* Defines for transitions of FSM */

#define IDLE_TO_OPEN_WALL_TRANSITION 0
#define OPEN_WALL_TO_OPEN_DOOR_TRANSITION 1
#define LEFT_CRATE_TO_RIGHT_CRATE_TRANSITION 2
#define LEFT_CRATE_TO_TOP_CRATE_TRANSITION 3
#define LEFT_CRATE_TO_BOTTOM_CRATE_TRANSITION 4
#define RIGHT_CRATE_TO_LEFT_CRATE_TRANSITION 5
#define RIGHT_CRATE_TO_TOP_CRATE_TRANSITION 6
#define RIGHT_CRATE_TO_BOTTOM_CRATE_TRANSITION 7
#define TOP_CRATE_TO_LEFT_CRATE_TRANSITION 8
#define TOP_CRATE_TO_RIGHT_CRATE_TRANSITION 9
#define TOP_CRATE_TO_BOTTOM_CRATE_TRANSITION 10
#define BOTTOM_CRATE_TO_LEFT_CRATE_TRANSITION 11
#define BOTTOM_CRATE_TO_RIGHT_CRATE_TRANSITION 12
#define BOTTOM_CRATE_TO_TOP_CRATE_TRANSITION 13
#define LEFT_CRATE_TO_CENTER_TRANSITION 14
#define RIGHT_CRATE_TO_CENTER_TRANSITION 15
#define TOP_CRATE_TO_CENTER_TRANSITION 16
#define BOTTOM_CRATE_TO_CENTER_TRANSITION 17
#define LEFT_CRATE_OUT_OF_CENTER_TRANSITION 18
#define RIGHT_CRATE_OUT_OF_CENTER_TRANSITION 19
#define TOP_CRATE_OUT_OF_CENTER_TRANSITION 20
#define BOTTOM_CRATE_OUT_OF_CENTER_TRANSITION 21

extern int FSM_table[10][10];

extern bool OPENED_FLAG;
extern int current_state;
extern int current_signal;

void FSM_table_init();
void FSM_classifier();

#endif /* FSM_H */